### PR TITLE
Replace deprecated g_settings_list_keys usage

### LINKED ISSUE #4: 'gchar** g_settings_list_keys(GSettings*)' is deprecated
```
qgsettings.cpp:108:55: warning: 'gchar** g_settings_list_keys(GSettings*)' is deprecated: Use 'g_settings_schema_list_keys' instead [-Wdeprecated-declarations]
  108 |     gchar **keys = g_settings_list_keys(priv->settings);
      |                                                       ^
```

### PR DESCRIPTION
**Pull request by z3ntu**
Fixes #4

### CODE REVIEW

**Review by mariogrip — APPROVED** [review]
LGTM :+1:

Merge after OTA-12 freeze
+ Merge to gitlab

**Comment by z3ntu** [comment]
@mariogrip Can you please change the default branch of this repository to xenial? I think that should also make github realize that it can close issue #4

**Comment by jezek** [comment]
There is a call for testing. How do we test this, please?

**Comment by UniversalSuperBox** [comment]
Given that system-settings and Lomiri appear to be functioning normally, QA is complete.

**Pull request merged**
